# Week 1: Clean the Airbnb Dataset (and Deploy It!)

Welcome to the first week's project for *Python for Data Science*!

This week's lecture and material on CoRise showed you how to effectively use NumPy to clean, read, and process data. Now having looked at the data, you might be thinking to yourself, "Why were these these latitude and longitude columns included in the dataset for Week 1?" 🤷 We'll put this data to use in this project, and also get a preview of how you will be expected to make forecasts of your own with this data at the end of this course! For this week's project, we are going to use that location data to make an interactive app. We hope this project gets you excited for what's to come in following weeks 🙌🙌! 

## Downloading the Dataset

You will need to download some prerequisite packages in order to run all the code below. Let's install them!

In [3]:
%%capture
!pip install numpy pandas streamlit gdown currencyconverter

In [4]:
import numpy as np

# For readability purposes, we will disable scientific notation for numbers
np.set_printoptions(suppress=True)

Taking a look at the `import` statements below shows that we are using a mix of Python out-of-the-box 🎁 libraries (os, shutil, gzip) alongside some custom ones (gdown, numpy). Gdown allows us to download files from Google Drive, which is where we saved our modified dataset. Gzip helps us unzip downloaded files. Shutil copies the downloaded files in the right location, and we'll use os to delete unneeded files.

In [5]:
import os
import shutil

import gdown
from numpy import genfromtxt

# Download file from Google Drive
# This file is based on data from: http://insideairbnb.com/get-the-data/
file_id_1 = "13fyESiH1ZEnMV6eabAyhe20t4W6peEWK"
downloaded_file_1 = "WK1_Airbnb_Amsterdam_listings_proj.csv"

# Download the file from Google Drive
gdown.download(id=file_id_1, output=downloaded_file_1)

Downloading...
From: https://drive.google.com/uc?id=13fyESiH1ZEnMV6eabAyhe20t4W6peEWK
To: C:\Users\HP\Desktop\PFD\WK1_Airbnb_Amsterdam_listings_proj.csv
100%|████████████████████████████████████████████████████████████████████████████████| 246k/246k [00:01<00:00, 194kB/s]


'WK1_Airbnb_Amsterdam_listings_proj.csv'

## Preprocessing the Dataset
Getting this particular dataset loaded is a tad bit different from what we learned in this week's content. This time we only have 1 CSV file, so we do not need to merge it. So because there is no need to merge we can move right into data preprocessing!

#### Task 1: Find your delimiter
Inspect the csv file we just downloaded and look at the type of delimiter it has. Once you've found the right delimiter, use the dtype "unicode". 

In [6]:
from numpy import genfromtxt

my_data = genfromtxt(downloaded_file_1, delimiter="|", dtype="unicode")

Next, output the first four columns for inspection to see if you've got the data formatted how you'd like.

In [7]:
my_data[:, :4]

array([['', '0', '1', '2'],
       ['id', '23726706', '35815036', '31553121'],
       ['price', '$88.00', '$105.00', '$152.00'],
       ['latitude', '52.34916', '52.42419', '52.43237'],
       ['longitude', '4.97879', '4.95689', '4.91821']], dtype='<U18')

Awesome! But notice our data is aligned a little differently than how we saw in the course materials. It's like we shifted our dataset by 90 degrees! You'll have to fix this a little bit later.

#### Task 2: Clean it up
In order for your calculations to run correctly, you need to have only the "relevant" numbers/entries present in your dataset. This means no headers, footers, redudant IDs, etc. Can you remove the first row and column, since you won't be needing them? Verify your work by again by printing out the first four columns.

In [9]:
# Remove the first column and row
matrix = my_data[1:, 1:]

# Print out the first four columns
matrix[:, :4]

array([['23726706', '35815036', '31553121', '34745823'],
       ['$88.00', '$105.00', '$152.00', '$87.00'],
       ['52.34916', '52.42419', '52.43237', '52.2962'],
       ['4.97879', '4.95689', '4.91821', '5.01231']], dtype='<U18')

#### Task 3: Wide to long
As stated previously, our dataset is shifted by 90 degrees. Let's shift it another 90 degrees to get it back to how we'd expect, which is in a much more readable format. Please find in the course material in CoRise the correct operation that you'd need to use to do that. Again, verify your work by printing out of the first five rows.

In [10]:
# Shift the matrix by 90 degrees
matrix = matrix.T

# Print out the first five rows
# Entries: airbnb_id, price_usd, latitude, longitude
matrix[:5, :]

array([['23726706', '$88.00', '52.34916', '4.97879'],
       ['35815036', '$105.00', '52.42419', '4.95689'],
       ['31553121', '$152.00', '52.43237', '4.91821'],
       ['34745823', '$87.00', '52.2962', '5.01231'],
       ['44586947', '$160.00', '52.31475', '5.0303']], dtype='<U18')

Now that all data is loaded properly, let's clean it up a bit like we did before by removing string characters and setting the right type 😁.

#### Task 4: That character is not appropriate

String characters like commas and dollar signs are yet again present in the dataset. Please find in the CoRise course materials the correct operation to filter out these two string characters from the dataset.

In [12]:
# Remove the dollar sign
matrix = np.char.replace(matrix, "$", "")

# Remove the comma
matrix = np.char.replace(matrix, ",", "")

Awesome! Now the dataset contains only numerical values allowing us to perform numerical operations... at least if we set the type right!

#### Task 5: Verification is the key to success!
Let's verify our matrix to confirm there are no more string characters present. Check to see if a dollar sign or comma still appears anywhere in the matrix. 


In [13]:
# Check if the dollar sign is in our dataset
matrix[np.char.find(matrix, "$") > -1]

array([], dtype='<U18')

In [14]:
# Check if the comma is in our dataset
matrix[np.char.find(matrix, ",") > -1]

array([], dtype='<U18')

In [15]:
# Change Unicode to float32
matrix = matrix.astype(np.float32)

# Print out the first five rows (and inspect the dtype for correctness)
# Entries: airbnb_id, price_usd, latitude, longitude
matrix[:5,:]

array([[23726706.     ,       88.     ,       52.34916,        4.97879],
       [35815036.     ,      105.     ,       52.42419,        4.95689],
       [31553120.     ,      152.     ,       52.43237,        4.91821],
       [34745824.     ,       87.     ,       52.2962 ,        5.01231],
       [44586948.     ,      160.     ,       52.31475,        5.0303 ]],
      dtype=float32)

<details>
  <summary>Show Expected Output</summary>

  
```
array([[23726706.     ,       88.     ,       52.34916,        4.97879],
       [35815036.     ,      105.     ,       52.42419,        4.95689],
       [31553120.     ,      152.     ,       52.43237,        4.91821],
       [34745824.     ,       87.     ,       52.2962 ,        5.01231],
       [44586948.     ,      160.     ,       52.31475,        5.0303 ]],
      dtype=float32)
```

<details>
<summary>Show Solution</summary>

```python
# Change unicode to float32
matrix = matrix.astype(np.float32)

# Print out the first five rows (and inspect the dtype for correctness)
matrix[:5, :]
```

</details>
</details>

## The Price Is Right

<center>
  <img src=https://wwwimage-tve.cbsstatic.com/thumbnails/photos/w400-q80/blog/tpir-logo-promo_0_0.jpg width="500" align="center" />
</center>
<br/>

Since all our values in the matrix are now recognized as numbers, we can perform some awesome calcultions! 

Our next objective is to change the currency from US dollars to another currency. This can be any currency you like, except for the US dollar. Let's first import the library that helps us to make these conversions. Then let's have another look at the first 5 rows of our matrix.

In [16]:
from currency_converter import CurrencyConverter

cc = CurrencyConverter()

# Entries: airbnb_id, price_usd, latitude, longitude
for c in matrix[:, 1]:
    cc.convert(c, "USD", "EUR")

The currency conversion calculations you'll be performing should be applied to the second column. 

As a reminder, you should use the number "1" which represents the second column of the matrix, since indexes start at the number zero.

Please only output the second column below:

In [17]:
matrix[:,1]

array([ 88., 105., 152., ..., 180., 174.,  65.], dtype=float32)

#### Task 7: Pick any currency

The tool you'll be using has a total of 42 currencies. Please select one of them, and use it to convert the dollars into your chosen currency. You can check which are available by running:

In [ ]:
cc.currencies

A suggestion for those who don't know which to choose: Feel free to use GBP.

In [18]:
# Get the rate of conversaton from the US dollar to your currency of choice
eur_rate = cc.convert(1, "USD", "EUR") # Euro

# Multiply the dollar column by your currency of choice
matrix[:, 1] = matrix[:, 1] * eur_rate

#### Task 8: Inflation!

Recent inflation all around the world has caused many companies to raise their prices. Consequently, Airbnb listings have also raised their prices by a certain amount. Find the 2022 annual inflation rate for your currency of choice. If you can't find the inflation rate online, use 7% as value. Apply this inflation rate to our newly updated prices.

In [19]:
# Multiply the dollar column by the inflation percentage (1.00 + inflation)
matrix[:, 1]  = matrix[:, 1] * 1.07

#### Task 9: Too many decimals!

You might have some prices longer than two decimals after changing the currency and adjusting the price for inflation. Please round the prices **down** to the nearest two decimals using a NumPy native function. [Here's a hint.](https://numpy.org/doc/stable/reference/generated/numpy.around.html)

In [21]:
# Round down the new currency column to 2 decimals
matrix[:, 1]  = np.around(matrix[:, 1], decimals=2)
matrix[:, 1]

array([ 87.07, 103.89, 150.4 , ..., 178.1 , 172.17,  64.31], dtype=float32)

## Where u (want to be) at?


<center>
  <img src=https://media.timeout.com/images/105504583/750/422/image.jpg width="500" align="center" />
</center>
<br/>

Amsterdam is a city with a long history and a rich international culture, so there is always [something interesting to see and do](https://www.iamsterdam.com/en/see-and-do/things-to-do/top-20-things-to-do-in-amsterdam). What if you were to visit Amsterdam? You'd probably want to have your Airbnb close to your favorite spot!

#### Task 10: Choose your location

Look up a place you'd like to visit in Amsterdam's city center, along with its longitude and latitude. We want to save this for choosing an Airbnb listing to our liking. You can get coordinates from [Google](https://www.google.com/) by searching like so:

<center>
  <img src=https://i.ibb.co/XXdkH3z/Screen-Shot-2022-10-24-at-2-42-54-PM.png width="500" align="center" />
</center>
<br/>




In [22]:
# Favorite location
latitude = 52.3600
longitude = 4.8852

## Listing All Listings

<center>
  <img src=https://images0.persgroep.net/rcs/vnd5KBhggcKV72YJjpLWH_-xljU/diocontent/131036963/_crop/34/170/1378/778/_fitwidth/763?appId=93a17a8fd81db0de025c8abd1cca1279&quality=0.8&desiredformat=webp width="500" align="center" />
</center>
<br/>

Imagine Airbnb Amsterdam decided to deviate from Airbnb Global and provide a feature on their website that showed the best listings for you based on the locations you were planning to visit. Wouldn't it make sense to choose a place to stay in a location closest to where you're likely to go most often?

So this is the most exciting part: You're going to calculate just that! You will limit your results to your favorite location in Amsterdam (as chosen above) and the surrounding available Airbnb listings using math and NumPy!

We've already provided you with the math calculations down below. Please make sure to run that method!

You'll have to use this method in a `for` loop or by using [`np.vectorize`](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html) as was shown on CoRise. 

In [24]:
import math

def from_location_to_airbnb_listing_in_meters(lat1: float, lon1: float, lat2: list, lon2: list):
    # Source: https://community.esri.com/t5/coordinate-reference-systems-blog
    # /distance-on-a-sphere-the-haversine-formula/ba-p/902128
    
    R = 6371000  # Radius of Earth in meters
    phi_1 = math.radians(lat1)
    phi_2 = math.radians(lat2)

    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)

    a = (
        math.sin(delta_phi / 2.0) ** 2
        + math.cos(phi_1) * math.cos(phi_2) * math.sin(delta_lambda / 2.0) ** 2
    )

    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    meters = R * c  # Output distance in meters

    return np.round(meters, 0)

#### Task 11: Loop or vectorize!

Please implement a `for` loop (or vectorize) the `from_location_to_airbnb_listing_in_meters` function. ***For now just calculate these numbers. Don't add it as a new column to your matrix.***

In [25]:
# Create a loop or vectorized way to calculate the distance,
# going over all latitude and longitude entries in the dataset

conv_to_meters = np.vectorize(from_location_to_airbnb_listing_in_meters)
conv_to_meters(latitude, longitude, matrix[:, 2], matrix[:, 3])

array([6469., 8638., 8353., ..., 7457., 4680., 5415.])

<details>
<summary>Show Solution</summary>

```python
# Allow a Python-function to be used in a (semi-)vectorized way.
conv_to_meters = np.vectorize(from_location_to_airbnb_listing_in_meters)

# Apply the function
conv_to_meters(latitude, longitude, matrix[:, 2], matrix[:, 3])
```

</details>

Now let's use the `timeit` function to see how quickly the code is ran!

In [26]:
%%timeit -r 4 -n 100

# Allow a Python function to be used in a (semi-)vectorized way
conv_to_meters = np.vectorize(from_location_to_airbnb_listing_in_meters)

# Apply the function, use timeit
conv_to_meters(latitude, longitude, matrix[:, 2], matrix[:, 3])

83.5 ms ± 1.15 ms per loop (mean ± std. dev. of 4 runs, 100 loops each)


## Can We Do It Faster?

Now you might be thinking to yourself, *can we do this faster*? 

The answer is ***YES***! 

But please remember that optimization is always a trade-off between the need for speed and the need for delivery of your results!

---

#### (Extra Credit)  Task 12: NumPy all the way!

Now convert the `from_location_to_airbnb_listing_in_meters` function into a pure NumPy function. You can do this by changing all the imported math functions into their NumPy variant. ***For now just calculate these numbers. Don't add it as a new column to your matrix.***

In [27]:
def from_location_to_airbnb_listing_in_meters(
    lat1: float, lon1: float, lat2: np.ndarray, lon2: np.ndarray
):
    R = 6371000  # radius of Earth in meters
    phi_1 = np.radians(lat1)
    phi_2 = np.radians(lat2)

    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)

    a = (
        np.sin(delta_phi / 2.0) ** 2
        + np.cos(phi_1) * np.cos(phi_2) * np.sin(delta_lambda / 2.0) ** 2
    )

    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    meters = R * c  # output distance in meters

    return np.round(meters, 0)

#### (Extra Credit) Task 13: How much faster is it?
Use the `timeit` function so we can compare it to the outcome of the prior task. This should be very similar to the `timeit`-code that was used below Task 11.

In [28]:
%%timeit -r 4 -n 100

# Copy the code from Task 12 and add a timeit function above this comment
def from_location_to_airbnb_listing_in_meters(
    lat1: float, lon1: float, lat2: np.ndarray, lon2: np.ndarray
):
    R = 6371000  # radius of Earth in meters
    phi_1 = np.radians(lat1)
    phi_2 = np.radians(lat2)

    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)

    a = (
        np.sin(delta_phi / 2.0) ** 2
        + np.cos(phi_1) * np.cos(phi_2) * np.sin(delta_lambda / 2.0) ** 2
    )

    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    meters = R * c  # output distance in meters

    return np.round(meters, 0)

938 ns ± 20.3 ns per loop (mean ± std. dev. of 4 runs, 100 loops each)


In [29]:
%%timeit -r 4 -n 100

from_location_to_airbnb_listing_in_meters(
    latitude, longitude, matrix[:, 2], matrix[:, 3]
)

537 µs ± 230 µs per loop (mean ± std. dev. of 4 runs, 100 loops each)


WOW! You see a massive speed-up just by switching your functions from default Python functions to their NumPy variants! Awesome!

---

## Prep the Dataset for Download!


Now that we've created a function to calculate the distance in meters for every Airbnb listing, we'll perform this calculation on the entire dataset and add the outputs to the matrix as a new column.

Next to that, we'll add another column that contains only ones and zeros to represent the "color" of an entry/row. This column can be used later if you want to turn this dataset into an app using [Streamlit](https://streamlit.io/). This resource is great for when you want to translate your Python projects into an interactive website. More on that in the next section.

As you'll see from the code, we'll also add our favorite location as an entry/row. (We've selected the coordinates of the Rijksmuseum. Feel free to change it to your favorite location in Amsterdam). 




In [30]:
# Run the previous method
meters = from_location_to_airbnb_listing_in_meters(
    latitude, longitude, matrix[:, 2], matrix[:, 3]
)

# Add an axis to make concatenation possible
meters = meters.reshape(-1, 1)

# Append the distance in meters to the matrix
matrix = np.concatenate((matrix, meters), axis=1)

In [31]:
# Append a color to the matrix
colors = np.zeros(meters.shape)
matrix = np.concatenate((matrix, colors), axis=1)

# Append our entry to the matrix
fav_entry = np.array([1, 0, 7.2300, 3.4387, 0, 1]).reshape(1, -1) # Change coordinates to your favorite location
matrix = np.concatenate((fav_entry, matrix), axis=0)

# Entries: airbnb_id, price, latitude, longitude,
# meters from favorite point, color
matrix[:5, :]

array([[       1.        ,        0.        ,        7.23      ,
               3.4387    ,        0.        ,        1.        ],
       [23726706.        ,       87.06999969,       52.34915924,
               4.97878981,     6469.        ,        0.        ],
       [35815036.        ,      103.88999939,       52.42419052,
               4.95689011,     8638.        ,        0.        ],
       [31553120.        ,      150.3999939 ,       52.43236923,
               4.91821003,     8353.        ,        0.        ],
       [34745824.        ,       86.08000183,       52.2961998 ,
               5.01231003,    11178.        ,        0.        ]])

In [32]:
# Export the data to use in the primer for next week
np.savetxt("WK1_Airbnb_Amsterdam_listings_proj_solution.csv", matrix, delimiter=",")

Great! By running all the cells above, you've saved the matrix here on your Google Colab instance. Let's now look into how to download the dataset to your local machine.

### Make an App for Your Portfolio!

<center>
  <img src=https://griddb-pro.azureedge.net/en/wp-content/uploads/2021/08/streamlit-1160x650.png width="500" align="center" />
</center>
<br/>

**Participants such as yourselves often want to use the weekly CoRise projects for their portfolios. To facilitate that, we've created this section. It might seem like a lot, but it's actually just following instructions and copy-pasting. Reach out on Slack if you get stuck!** 

You will make an app that visualizes the dataset as a DataFrame and as a geographic visualization like:

<center>
  <img src=https://i.ibb.co/gRhj6Jd/Screen-Shot-2022-11-10-at-3-58-17-PM.png width="500" align="center" />
</center>
<br/>

Five out of the six columns in the dataset are used as so:
- **Listing_id**: Ignored for visualization purposes
- **Price**: Hovering over a blue/red dot displays in **bold** the price at the top
- **Latitude**: Used to plot the blue/red dot on the map
- **Longitude**: Used to plot the blue/red dot on the map
- **Meters from favorite point**: Hovering over a blue/red dot displays the number of meters from the blue point
- **Color**: Dependent on the category its assigned

To visualize this, we will again use a library called [Streamlit](https://streamlit.io/). For now you are not expected to know how Streamlit works, but you are expected to be able to copy-paste and follow instructions if you want to share this project as part of your portfolio!

We are going to use [Streamlit Share](https://share.streamlit.io/) to host your projects. It's a website that allows us to host our interactive projects for free online! Again, we don't expect you to understand how to use and/or modify the code we will show below. We do expect you to read the instructions and copy-paste our code to the Streamlit Share platform. Feel free to change it any way you like. Some great starting points are [here](https://python.plainenglish.io/how-to-build-web-app-using-streamlit-pandas-numpy-5e134f0cf552), [here](https://docs.streamlit.io/library/get-started/create-an-app), [here](https://streamlit.io/components), and [here](https://streamlit.io/gallery)!

*Please make sure to change the currency symbol in the code below to the appropriate one if you've chosen something other than GBP/pound.*

In [35]:
%%writefile streamlit_app.py
import pandas as pd
import plotly.express as px
import streamlit as st

# Display title and text
st.title("Week 1 - Data and visualization")
st.markdown("Here we can see the dataframe created during this weeks project.")

# Read dataframe
dataframe = pd.read_csv(
    "WK1_Airbnb_Amsterdam_listings_proj_solution.csv",
    names=[
        "Airbnb Listing ID",
        "Price",
        "Latitude",
        "Longitude",
        "Meters from chosen location",
        "Location",
    ],
)

# We have a limited budget, therefore we would like to exclude
# listings with a price above 100 pounds per night
dataframe = dataframe[dataframe["Price"] <= 100]

# Display as integer
dataframe["Airbnb Listing ID"] = dataframe["Airbnb Listing ID"].astype(int)
# Round of values
dataframe["Price"] = "€ " + dataframe["Price"].round(2).astype(str)
# Rename the number to a string
dataframe["Location"] = dataframe["Location"].replace(
    {1.0: "To visit", 0.0: "Airbnb listing"}
)

# Display dataframe and text
st.dataframe(dataframe)
st.markdown("Below is a map showing all the Airbnb listings with a red dot and the location we've chosen with a blue dot.")

# Create the plotly express figure
fig = px.scatter_mapbox(
    dataframe,
    lat="Latitude",
    lon="Longitude",
    color="Location",
    color_discrete_sequence=["blue", "red"],
    zoom=11,
    height=500,
    width=800,
    hover_name="Price",
    hover_data=["Meters from chosen location", "Location"],
    labels={"color": "Locations"},
)
fig.update_geos(center=dict(lat=dataframe.iloc[0][2], lon=dataframe.iloc[0][3]))
fig.update_layout(mapbox_style="stamen-terrain")

# Show the figure
st.plotly_chart(fig, use_container_width=True)

Overwriting streamlit_app.py


The **%%writefile [FILE_NAME].[FILE_EXTENSION]** command let's us save the code written in the cells in your Google Colab instance. Having it saved like that enables us to download it as a file, as seen below:

In [36]:
%%writefile requirements.txt
pandas
streamlit
plotly

Overwriting requirements.txt
